# Generated by Django 5.1.4 on 2025-02-08 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(max_length=100)),
                ('lead_stage', models.CharField(choices=[('New', 'New'), ('Hot', 'Hot'), ('Contacted', 'Contacted'), ('Follow_Up', 'Follow_Up'), ('Closed_Won', 'Closed_Won'), ('Closed_Lost', 'Closed_Lost')], max_length=20)),
                ('lead_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_closing_date', models.DateField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_content', models.TextField(blank=True, null=True)),
                ('campaign_terms', models.TextField(blank=True, null=True)),
                ('caller_name', models.CharField(max_length=100)),
                ('call_duration', models.IntegerField(help_text='Call duration in seconds')),
                ('reason_not_connected', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('last_call_time', models.DateTimeField(blank=True, null=True)),
                ('last_call_status', models.CharField(max_length=100)),
                ('last_call_remarks', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('lead_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=20)),
                ('reports_to', models.ForeignKey(blank=True, help_text='The supervisor this user reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
