# Generated by Django 5.1.4 on 2025-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companyname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
