# Generated by Django 5.1.5 on 2025-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0004_userprofile_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='leadsforms',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Call duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='leadsforms',
            name='caller_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leadsforms',
            name='last_call_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
